### ISSUE TITLE
Handle concurrent customers

### ISSUE THREAD

**Issue by craigjbass** [craigjbass/pratura#11]

**Comment by tomverran** [comment]
I would be surprised if this involved any actual coding?

**Comment by craigjbass** [comment]
It does because currently there is one basket for all customers, which would get pretty annoying above 1 concurrent customer

**Comment by craigjbass** [comment]
I think a usecase around creating a basket and then having to pass an ID in. Obv probably encoded in jwt for the HTTP part

**Comment by tomverran** [comment]
Ah I see ,crikey
